import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CtaBand, PageHero } from "@/components/site-layout";
import { DetailList } from "@/components/service-sections";
import medicalImage from "@/assets/medical-care.jpg";

export const Route = createFileRoute("/assistance-medicale")({ head: () => ({ meta: [
  { title: "Assistance médicale en Tunisie — LASISTANT.PRO" }, { name: "description", content: "Préparation du séjour, démarches et orientation vers les professionnels de santé compétents en Tunisie." }, { property: "og:title", content: "Assistance médicale en Tunisie — LASISTANT.PRO" }, { property: "og:description", content: "Un interlocuteur attentif pour préparer et faciliter votre parcours de soins." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }, { property: "og:url", content: "/assistance-medicale" },
], links: [{ rel: "canonical", href: "/assistance-medicale" }] }), component: MedicalPage });

function MedicalPage() { return <><PageHero eyebrow="Assistance médicale" title="Préparer votre parcours de soins avec sérénité." intro="Nous vous aidons à structurer votre demande, à préparer votre séjour et à vous orienter vers les professionnels de santé compétents en Tunisie."><Button asChild size="lg" className="rounded-full"><Link to="/reservation" search={{ service: "Assistance médicale" }}>Présenter mon besoin <ArrowRight /></Link></Button></PageHero><section className="page-shell section-space grid gap-12 md:grid-cols-2 md:items-center"><img src={medicalImage} alt="Échange attentif autour d’un parcours de soins" width="1200" height="912" className="aspect-[4/3] rounded-md object-cover"/><div><p className="eyebrow">Ce que nous facilitons</p><h2 className="mt-4 text-3xl font-semibold">Un parcours mieux préparé, étape par étape.</h2><div className="mt-7"><DetailList items={["Étude de votre besoin et des informations disponibles.","Orientation vers les interlocuteurs et professionnels adaptés.","Préparation pratique du séjour et des démarches nécessaires.","Coordination avec les autres besoins : accueil, transport ou hébergement."]}/></div></div></section><section className="bg-muted"><div className="page-shell py-10"><p className="max-w-4xl text-sm leading-7 text-muted-foreground"><strong className="text-foreground">Important :</strong> LASISTANT.PRO facilite les démarches et l’orientation. Nous ne réalisons aucun diagnostic, acte médical ou prescription et ne nous substituons jamais aux professionnels de santé.</p></div></section><CtaBand /></> }